name: TripleRiderHorse
version: 1.0
main: com.nonkungch.triplerider.TripleRiderPlugin
api-version: 1.21 
authors: [NonKungCh]
description: Allows multiple players to ride a single horse, configurable via max-riders and in-game commands.

commands:
  triplerider:
    description: Main command for TripleRiderHorse plugin.
    usage: /triplerider <reload|setmax>
    permission: triplerider.admin

permissions:
  triplerider.admin:
    description: Allows reloading and setting max riders.
    default: op
