name: Build TripleRiderHorse Plugin

# เงื่อนไขการสั่งให้ Action ทำงาน
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout โค้ด
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # 2. ตั้งค่า Java JDK: ใช้เวอร์ชัน 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3. Build Project ด้วย Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # 4. ค้นหา JAR Artifact
      - name: Find Artifact JAR
        id: find_jar
        run: |
          echo "JAR_PATH=$(find target/ -name 'TripleRiderHorse-Plugin-*.jar' -print -quit)" >> $GITHUB_ENV

      # 5. Upload Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TripleRiderHorse-Plugin
          path: ${{ env.JAR_PATH }}
          if-no-files-found: error
